account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('signup', views.signup, name='signup'),
    path('home', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('structure', views.structure, name='structure'),
    path('invited', views.invited, name='invited'),
    path('invited_ajax', views.invited_ajax, name='invited_ajax'),
    path('bonus_history', views.bonus_history, name='bonus_history'),
    path('validate_username_ajax', views.validate_username_ajax, name='validate_username_ajax'),
    path('documentation', views.documentation, name='documentation'),
    path('notifications', views.notifications, name='notifications'),
]

graph/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from graph.views import ModelListGraphsView, ModelGraphView, ModelGraphInlineView

app_name = 'graph'

urlpatterns = [
    url(r'^(?P<modpath>[-._\w]+)/(?P<pk>[0-9]+)/$', ModelGraphInlineView.as_view(), name="mpttgraph-inline"),
    url(r'^(?P<modpath>[-._\w]+)/(?P<pk>[0-9]+)/$', ModelGraphView.as_view(), name="mpttgraph-detail"),
    url(r'^', ModelListGraphsView.as_view(), name="mpttgraph-index"),
]

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', MainPage, name='MainPage'),
    path('news', NewsList, name='NewsList'),
    path('news/<int:id>', NewsDetail, name='NewsDetail'),
    path('slides/<int:id>', SlideDetail, name='SlideDetail'),
]

richclub/urls.py
from django.urls import include, path
from django.contrib import admin


admin.site.site_title = ''
admin.site.site_header = 'Администрирование'
admin.site.index_title = ''

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('account/', include('account.urls')),
    path('graph/', include('graph.urls')),
]

graph/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from mptt.models import TreeForeignKey, MPTTModel


class GraphModel(models.Model):
    title = models.CharField(max_length=200, verbose_name=_(u"Title"))
    model_path = models.CharField(max_length=200, verbose_name=_(u"Model path"),
                                  help_text=_(u"Path to the model: ex: "
                                              "myapp.models.MyModel"))
    model_pk = models.PositiveSmallIntegerField(
        verbose_name=_(u"Root node primary key"))

    class Meta:
        verbose_name = _(u'Mptt graph')
        verbose_name_plural = _(u'Mptt graphs')
        ordering = ('title',)

    def __str__(self):
        return self.title


class TreeNode(MPTTModel):
    title = models.CharField(max_length=200, verbose_name=_(u"Title"))
    parent = TreeForeignKey('self', null=True, blank=True, related_name=u'children',
                            verbose_name=_(u'Parent node'), on_delete=models.CASCADE)

    class Meta:
        verbose_name = _(u'Tree node')
        verbose_name_plural = _(u'Tree nodes')
        ordering = ('title',)

    def __str__(self):
        return self.title

graph/views.py
# -*- coding: utf-8 -*-
from django.db.models import Q
from django.http.response import Http404
from django.views.generic import TemplateView
from graph.models import GraphModel
from graph.utils import get_model_from_path
from account.models import Node


class ModelListGraphsView(TemplateView):
    template_name = 'graph/index.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_staff:
            raise Http404
        return super(ModelListGraphsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ModelListGraphsView, self).get_context_data(**kwargs)
        context['graphs'] = GraphModel.objects.all()
        return context


class ModelGraphView(TemplateView):
    template_name = 'graph/tree.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_staff:
            raise Http404
        return super(ModelGraphView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ModelGraphView, self).get_context_data(**kwargs)
        # model = get_model_from_path(self.kwargs['modpath'])
        root_node_pk = self.kwargs['pk']
        root_node = Node.objects.get(pk=root_node_pk)

        nodes = Node.objects.filter(Q(parent=root_node) | Q(pk=root_node_pk))

        context['nodes'] = nodes
        context['root_id'] = root_node_pk
        context['total_count'] = root_node.children.count()
        return context


class ModelGraphInlineView(ModelGraphView):
    template_name = 'graph/tree_inline.html'

graph/templates/graph/index.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{% trans "Model graphs" %}{% endblock title %}

{% block content %}
<h1 style="margin-bottom:1em">{% trans "Model graphs" %}</h1>
{% for graph in graphs %}
	<div style="display:inline;padding:1em;margin:1em;border:1px solid grey;border-radius:5px">
		<a href="{% url 'mpttgraph-detail' graph.model_path graph.model_pk %}">{{ graph.title }}</a>
	</div>
{% endfor %}
{% endblock content %}

graph/templates/graph/tree.html
{% extends "base.html" %}
{% load static mptt_tags %}

{% block title %}Model graph{% endblock title %}

{% block content %}
<link rel="stylesheet" media="screen, projection" href="{% static 'graph/tree.css' %}" />
<div class="row">
	<div class="col-xs-12">
		<div class="text-center" style="width:100%;font-size:65%">
			<div class="text-left" style="display:inline-block">
				<div class="tree">
					<ul>
					{% recursetree nodes %}
				        <li>
				        	<a href="{% if node.url %}{{ node.url }}{% else %}{{ node.get_absolute_url }}{% endif %}" id="{{ id }}">
				            	{{ node.title }}{{ node.name }}
				            	<div id="displayzone_{{ id }}" class="displayzone"></div>
				            </a>
				            {% if not node.is_leaf_node %}
				                <ul>
				                    {{ children }}
				                </ul>
				            {% endif %}
				        </li>
				    {% endrecursetree %}
				    </ul>
			    </div>
			</div>
	    </div>
	</div>
</div>
{% endblock content %}

graph/templates/graph/tree_inline.html
{% extends "base.html" %}
{% load static mptt_tags %}

{% block sidebar %}
	<div class="sidebar" data-background-color="white" data-active-color="danger">
    <!--
		Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
		Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
	-->
    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="" class="simple-text">
                    Rich Club
                </a>
            </div>
            <ul class="nav">
                <li>
                    <a href="{% url 'account:home' %}">
                        <i class="ti-home"></i>
                        <p>Общая сводка</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:profile' %}">
                        <i class="ti-user"></i>
                        <p>Профиль</p>
                    </a>
                </li>
                <li class="active">
                    <a href="">
                        <i class="ti-view-list-alt"></i>
                        <p>Структура</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:invited' %}">
                        <i class="ti-user"></i>
                        <p>Приглашенные</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:bonus_history' %}">
                        <i class="ti-server"></i>
                        <p>История бонусов</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:documentation' %}">
                        <i class="ti-map"></i>
                        <p>Документация</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'account:notifications' %}">
                        <i class="ti-bell"></i>
                        <p>Уведомления</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>
{% endblock %}

{% block content %}
    <link rel="stylesheet" media="screen, projection" href="{% static 'graph/tree.css' %}" />
        <div class="content">
            <div class="container-fluid">
                <a href="{% url 'account:structure' %}">Показать списком</a>
               <div class="row">
                   Общее количество: {{ total_count }}
               </div>
                   <div class="row">
                       {%if user.is_authenticated%}
                                {%if user.node.id|slugify != root_id|slugify %}
                                            <a style="border-width: 0px;" href="http://rich-club.org/graph/account.models.Node/{{user.node.id}}/" id="{{ user.node.id }}">Назад</a>
                                {% endif %}
                       {% endif %}
                    </div>
	<div class="text-left" style="width: 2000px; display:inline-block; overflow-x:scroll">
		<div class="tree">
			<ul>
			{% recursetree nodes %}
		        <li>
		        	<!--<a style="border-width: 0px;" href="{% if node.url %}{{ node.url }}{% else %}{{ node.get_absolute_url }}{% endif %}" id="{{ id }}">-->
                    <a style="border-width: 0px;" href="http://rich-club.org/graph/account.models.Node/{{ node.id }}/" id="{{ node.id }}">
                        <div class="logo-container">
                        <div class="logo">
                            <img style="border-radius: 50%;" src="{% static 'account/img/new_logo.png' %}"/>
                        </div>
                                {% if node.status == 0 %}
                                    <div class="brand" style="color: red">
                                         Id={{ node.pk }} {{ node.user.username }}
                                    </div>
                                {% endif %}
                                {% if node.status > 0 %}
                                    <div class="brand">
                                         Id={{ node.pk }} {{ node.user.username }}
                                    </div>
                                {% endif %}
                        </div>
		            	<div id="displayzone_{{ id }}" class="displayzone"></div>
		            </a>
		            {% if not node.is_leaf_node %}
		                <ul>
		                    {{ children }}
		                </ul>
		            {% endif %}
		        </li>
		    {% endrecursetree %}
		    </ul>
	    </div>
	</div>
                </div>
            </div>
        </div>
{% endblock %}
 {% block footer %}
{% endblock %}