account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('signup', views.signup, name='signup'),
    path('home', views.home, name='home'),
    path('profile', views.profile, name='profile'),
    path('structure', views.structure, name='structure'),
    path('invited', views.invited, name='invited'),
    path('invited_ajax', views.invited_ajax, name='invited_ajax'),
    path('bonus_history', views.bonus_history, name='bonus_history'),
    path('validate_username_ajax', views.validate_username_ajax, name='validate_username_ajax'),
    path('documentation', views.documentation, name='documentation'),
    path('notifications', views.notifications, name='notifications'),
]

main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', MainPage, name='MainPage'),
    path('news', NewsList, name='NewsList'),
    path('news/<int:id>', NewsDetail, name='NewsDetail'),
    path('slides/<int:id>', SlideDetail, name='SlideDetail'),
]

richclub/urls.py
from django.urls import include, path
from django.contrib import admin


admin.site.site_title = ''
admin.site.site_header = 'Администрирование'
admin.site.index_title = ''

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('account/', include('account.urls')),
    path('graph/', include('graph.urls')),
]

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
{% block head %}
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'account/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static 'account/img/favicon.png' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Rich Club</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="{% static 'account/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'account/css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Paper Dashboard core CSS    -->
    <link href="{% static 'account/css/paper-dashboard.css' %}" rel="stylesheet"/>

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'account/css/demo.css' %}" rel="stylesheet" />
    <!--<link href="{% static 'graph/tree.css' %}" rel="stylesheet" />-->
    <!--  Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'account/css/themify-icons.css' %}" rel="stylesheet">
<link href="{% static 'account/css/style.css' %}" rel="stylesheet"/>
</head>
{% endblock %}

<body>
                {% if user.is_authenticated %}
                     <input type="hidden" id="nodeId" name="nodeId" value="{{ user.node.id }}">
                {% endif %}
<div class="wrapper">
{% block sidebar %}
	<div class="sidebar" data-background-color="white" data-active-color="danger">

    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="" class="simple-text">
                    Rich Club
                </a>
            </div>
            <ul class="nav">
                <li >
                    <a href="home.html">
                        <i class="ti-home"></i>
                        <p>Общая сводка</p>
                    </a>
                </li>
                <li>
                    <a href="structure.html">
                        <i class="ti-view-list-alt"></i>
                        <p>Структура</p>
                    </a>
                </li>
                <li>
                    <a href="invited.html">
                        <i class="ti-user"></i>
                        <p>Приглашенные</p>
                    </a>
                </li>
                <li>
                    <a href="documentation.html">
                        <i class="ti-map"></i>
                        <p>Документация</p>
                    </a>
                </li>
                <li>
                    <a href="notifications.html">
                        <i class="ti-bell"></i>
                        <p>Уведомления</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>
{% endblock %}
    <div class="main-panel">
{% block navbar %}
    	<nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#"></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
						<li>
                            <a href="#">
								<i class="ti-settings"></i>
								<p>Настройки</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-user"></i>
									<p></p>
									<b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'account:user_logout' %}">Выйти</a></li>
                              </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
{% endblock %}
{% block content %}

{% endblock %}

        {% block footer %}
        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                    </ul>
                </nav>
				<div class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script>, разработано <a href="">Ananasit</a>
                </div>
            </div>
        </footer>
{% endblock %}
    </div>
</div>
</body>

    <!--   Core JS Files   -->
    <script src="{% static 'account/js/jquery.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'account/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<!--  Checkbox, Radio & Switch Plugins -->
	<script src="{% static 'account/js/bootstrap-checkbox-radio.js' %}"></script>

	<!--  Charts Plugin -->
	<script src="{% static 'account/js/chartist.min.js' %}"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'account/js/bootstrap-notify.js' %}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

    <!-- Paper Dashboard Core javascript and methods for Demo purpose -->
	<script src="{% static 'account/js/paper-dashboard.js' %}"></script>

	<!-- Paper Dashboard DEMO methods, don't include it in your project! -->
	<script src="{% static 'account/js/demo.js' %}"></script>

 {% block javascript %}
     <!--<script type="text/javascript">
    	$(document).ready(function(){
        	demo.initChartist();
        	$.notify({
            	icon: 'ti-gift',
            	message: "Welcome to <b>Paper Dashboard</b> - a beautiful Bootstrap freebie for your next project."
            },{
                type: 'success',
                timer: 4000
            });
    	});
	</script>-->
 {% endblock %}
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block sidebar %}
{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-default">
            <div class="container-fluid">
                 <div class="row">
                       {% if alert %}
                     <div class="alert alert-warning">
        <span><b> {{ alert }}</b></span>
    </div>
                     {% endif %}
                 </div>
            </div>
        </nav>
{% endblock %}
{% block content %}
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                      <div class="col-lg-8 col-md-7">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Вход</h4>
                            </div>
                            <div class="content">
                                <form action="{% url 'account:user_login' %}" method="post">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <label>ID</label>
                                                <input type="text" name="username" class="form-control border-input" placeholder="ID">
                                            </div>
                                        </div>
                                            <div class="col-md-5">
                                            <div class="form-group">
                                                <label>Пароль</label>
                                                <input type="text" name="password" class="form-control border-input" placeholder="Пароль">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-info btn-fill btn-wd">Войти</button>
                                    </div>
                                    <br/>
                                    <div class="row">
                                        <div class="text-center">
                                            <a href="{% url 'account:signup' %}">Регистрация</a>
                                    </div>
                </div>
                                    <div class="clearfix"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}